# freeradius_config/clients.conf

client dockernet {
    ipaddr = 0.0.0.0/0
    secret = s3m_test_secret_key
    require_message_authenticator = no
}

client localhost {
    ipaddr = 127.0.0.1
    secret = s3m_test_secret_key
    require_message_authenticator = no
}
